import { Routes } from "@angular/router";
import { HomeComponent } from "./pages/home/home.component";
import { AgentsComponent } from "./components/agents/agents.component";
import { MapsComponent } from "./pages/maps/maps.component";
import { StatsComponent } from "./pages/stats/stats.component";
import { AgentsDetailsComponent } from "./components/agents-details/agents-details.component";
import { MapStratComponent } from "./components/map-strat/map-strat.component";
import { WeaponsComponent } from "./pages/weapons/weapons.component";
import { LoginComponent } from "./pages/login/login.component";
import { SignupComponent } from "./pages/signup/signup.component";
import { DashboardComponent } from "./pages/dashboard/dashboard.component";
import { NotFoundComponent } from "./pages/not-found/not-found.component";
import { ListMatchesComponent } from "./components/list-matches/list-matches.component";
import { EsportsComponent } from "./pages/esports/esports.component";
import { TeamsDetailsComponent } from "./components/teams-details/teams-details.component";
import { AgentsListDashboardComponent } from "./pages/agents-list-dashboard/agents-list-dashboard.component";
import { WeaponsListDashboardComponent } from "./pages/weapons-list-dashboard/weapons-list-dashboard.component";
import { MatchesDashboardComponent } from "./pages/matches-dashboard/matches-dashboard.component";

export const routes: Routes = [
  { path: "", redirectTo: "Home", pathMatch: "full" },
  { path: "Home", component: HomeComponent },
  { path: "agents", component: AgentsComponent },
  { path: "weapons", component: WeaponsComponent },
  { path: "maps", component: MapsComponent },
  { path: "list-matches", component: ListMatchesComponent },
  { path: "stats", component: StatsComponent },
  { path: "agents/:id", component: AgentsDetailsComponent },
  { path: "maps-strat/:uuid", component: MapStratComponent },
  { path: "signup", component: SignupComponent },
  { path: "dashboard", component: DashboardComponent },
  { path: "login", component: LoginComponent },
  { path: "esports", component: EsportsComponent },
  { path: "teams-details", component: TeamsDetailsComponent },
  { path: "**", component: NotFoundComponent },
  { path: "agents-list-dashboard", component: AgentsListDashboardComponent },
  { path: "weapons-list-dashboard", component: WeaponsListDashboardComponent },
  { path: "matches-dashboard", component: MatchesDashboardComponent },
];
