export const DUMMY_MAPS = [{
    id: "ascent",
    name: "Ascent",
    description: "Una mappa ambientata in Italia con ampie aree aperte e porte a chiusura meccanizzata.",
    image: "assets/maps/ascent.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch", "Team Deathmatch", "Escalation"],
}, 
{
    id:"abyss",
    name:"Abyss",
    description:" Ambientata in una base sotterranea segreta, Abyss è la prima mappa di Valorant a non avere confini esterni, presentando invece zone denominate death drop in cui i giocatori possono cadere nel vuoto, risultando in una morte istantanea.",
    image:"assets/maps/abyss.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
{
    id: "bind",
    name: "Bind",
    description: "Due siti senza mid, ma con teletrasporti unidirezionali per rotazioni rapide.",
    image: "assets/maps/bind.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
{
    id: "haven",
    name: "Haven",
    description: "L'unica mappa con tre siti di impianto, che offre più possibilità strategiche.",
    image: "assets/maps/haven.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
{
    id: "split",
    name: "Split",
    description: "Caratterizzata da aree rialzate e corde, favorisce il controllo della mappa con utility.",
    image: "assets/maps/split.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
{
    id: "icebox",
    name: "Icebox",
    description: "Una mappa ghiacciata con molte zipline e verticalità elevata.",
    image: "assets/maps/icebox.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
{
    id: "breeze",
    name: "Breeze",
    description: "Una mappa tropicale con ampi spazi aperti e lunghe linee di tiro.",
    image: "assets/maps/breeze.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
{
    id: "fracture",
    name: "Fracture",
    description: "Mappa unica con un design a 'H', dove i difensori iniziano al centro.",
    image: "assets/maps/fracture.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
{
    id: "pearl",
    name: "Pearl",
    description: "Mappa sottomarina con design più tradizionale senza meccaniche uniche.",
    image: "assets/maps/pearl.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
{
    id: "lotus",
    name: "Lotus",
    description: "Mappa con tre siti, con porte rotanti e nuove possibilità tattiche.",
    image: "assets/maps/lotus.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
{
    id: "sunset",
    name: "Sunset",
    description: "Mappa ambientata a Los Angeles con una disposizione classica a due siti.",
    image: "assets/maps/sunset.png",
    modes: ["Unrated", "Competitive", "Spike Rush", "Deathmatch","Team Deathmatch", "Escalation"],
},
]
